name: Test and coverage

on: [ push, pull_request ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: 1.17
      - name: Run coverage
        run: make coverage
      - name: Upload coverage to Codecov
        run: bash <(curl -s https://codecov.io/bash)
