---
name: "Lint and test"
on:
  push:
    tags:
      - v*
    branches:
      - master
  pull_request:
jobs:
  golangci-lint:
    strategy:
      matrix:
        go-version: [1.18.1]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: 1.18.1
      - name: lint
        uses: golangci/golangci-lint-action@v3.1.0
        with:
          version: latest
  tests:
    needs: golangci-lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.18.1
      - name: Run tests and coverage
        run: make test
